### ISSUE TITLE
Seems it does not work with heic images format.

### ISSUE THREAD

**Issue by Cristian98149** [lene/DuplicateImages#1]
Hi,
I tested the software with jpg and png images and it works correctly but not with heic images.

It is correct or I'm missing something?

Thanks

**Comment by lene** [comment]
That's true, heic format is not supported. I'll look into adding it ASAP!

**Comment by bigcat88** [comment]
Suggest to use [pillow-heif](https://github.com/bigcat88/pillow_heif)
Me and my friend use it in one app to detect duplicate images, and i am the developer of both...

**Comment by lene** [comment]
If you are still interested, you can use the new version's HEIC support by doing
```shell
$ pip install duplicate_images~=0.6.0
```
(or whichever your preferred method is).

I haven't tested HEIC extensively so YMMV. I am closing this issue though, in case of trouble with HEIC files please file a new bug.

**Comment by lene** [comment]
> Suggest to use [pillow-heif](https://github.com/bigcat88/pillow_heif) Me and my friend use it in one app to detect duplicate images, and i am the developer of both...

Thanks for the advice, @bigcat88! Using `pillow_heif` was easy and painless.
