### ISSUE TITLE
unable to change hash alorithm or hash size!

### ISSUE THREAD

**Issue by prajwalJumde** [lene/DuplicateImages#10]
whenever I use -
**_find-dups "out_2k1" --algorithm ahash --parallel --progress --hash-db hashes.json --slow_** 

I get the error - **_ValueError: Algorithm mismatch: phash != ahash_**

Similar thing hapens when I change hash-size

**Comment by lene** [comment]
Hi and sorry for the late reply!

Currently it is not possible to store either hashes for multiple algorithms, or for the same algorithm but different hash sizes, in the same hash-db file. To get rid of the `ValueError`, please use the script like this (for example):
```
$ find-dups "out_2k1" --algorithm phash --parallel --progress --hash-db hashes.phash.json --slow
$ find-dups "out_2k1" --algorithm ahash --parallel --progress --hash-db hashes.ahash.json --slow
```
(I have to remark that, unless you use the `--max-distance` option, the `--slow` option is completely useless and does nothing but slow down operation, by a considerable amount if the number of images is big)
Or, for different hash sizes,
```
$ find-dups "out_2k1" --algorithm phash --parallel --progress --hash-db hashes.phash.8.json
$ find-dups "out_2k1" --algorithm phash --hash-size 10 --parallel --progress --hash-db hashes.phash.10.json
```

**Comment by lene** [comment]
Closing because no further feedback, assuming solved
