### ISSUE TITLE
Better algorithms are needed

### ISSUE THREAD

**Issue by ndvbd** [lene/DuplicateImages#12]
all fail to detect an image which is 1 deg rotated, except for the colorhash, but colorhash has plenty of false positive in other cases. why dont you have some keypoint+SIFT based algorithms?

**Comment by lene** [comment]
The library is relying on the [ImageHash](https://pypi.org/project/ImageHash/) library, which only supports the algorithms present. I am not famoliar with Keypoint  and SIFT matching, only did a quick search on it, but based on that search its use case is not really image similarity but finding equal points in different images. If you can point me to some documentation about how to use it for matching entire images, I'd be happy to look into it, but I cannot promise anything tbh.

**Comment by ndvbd** [comment]
Thank you!
