### ISSUE TITLE
Reliability and configuration

### ISSUE THREAD

**Issue by sla-te** [lene/DuplicateImages#3]
I am using it on around 10.000 images and finding a lot of duplicates - Now I don't want to make a mistake here and filter out duplicates, that actually aren't duplicates. How would you recommend me to configure `--max-distance --hash-size` to achieve a configuration, that will really only sort out the image if it is an **exact** duplicate.

My image set contains of images with an average size of 128x128 (png).

**Comment by chiburawk** [comment]
For future reference for two hashes (photos) to be equal, Hamming distance should be equal to 0. In this case I'd also make hash size a bit bigger than default 8, to be sure. Thus the parameters I'd use:
--max-distance 0
--hash-size 16
But you should always run your own tests just to be sure and not delete valuable info
