### ISSUE TITLE
Feat. Request: Exclude Folders

### ISSUE THREAD

**Issue by scharc** [lene/DuplicateImages#7]
I would love the option to exclude some directories or patterns from the root dir. Like caching directories.

My solution right now is to move the directories temporarily to some other dir to exclude them

**Comment by lene** [comment]
That's a good suggestion, thank you! I should be able to work on it soon.

**Comment by lene** [comment]
Added the command line switch `--exclude-dir` (which can take multiple directories as well as regular expressions) in version 0.10.5. It is available at https://pypi.org/project/duplicate_images/ now.
